return {
  cmd = { "basedpyright-langserver", "--stdio" },
  filetypes = { "python" },
  root_markers = { "pyproject.toml", "setup.py", "setup.cfg", "requirements.txt", "pyrightconfig.json", ".git" },
  settings = {
    basedpyright = {
      disableLanguageServices = false,
      disableOrganizeImports = true,
      disableTaggedHints = false,
      analysis = {
        autoImportCompletions = false,
        autoSearchPaths = true,
        diagnosticMode = "openFilesOnly",
        diagnosticSeverityOverrides = {},
        logLevel = "Warning",
        exclude = {
          "**/__pycache__",
          "**/node_modules",
          "build",
          "dist",
          "tests",
          ".vscode",
          ".idea",
          ".git",
          ".venv",
        },
        ignore = {
          "**/__pycache__",
          "**/node_modules",
          "build",
          "dist",
          "tests",
          ".vscode",
          ".idea",
          ".git",
          ".venv",
        },
        include = { "src" },
        stubPath = vim.fn.stdpath("data") .. "/lazy/python-type-stubs",
        typeCheckingMode = "standard",
        typeshedPaths = { vim.fn.stdpath("data") .. "/lazy/typeshed" },
      },
    },
  },
}
